package me.randomHashTags.RandomPackage.api.enums;

public enum RPConfigs {
	SOUNDS,
	KIT_DATA,
	MESSAGES, COMMANDS_FEATURES, MASTER, SHOP, GKITS, VKITS, DROP_PACKAGES, OTHER_GUIS,
	ENCHANTMENTS, ENCHANTMENTS_INFO,
}
