package me.randomHashTags.RandomPackage.api.enums;

public enum RPItem {
    RANDOM_BOOK,
    GOD_DP, GOD_RANDOMIZATION_SCROLL,
    SOUL_BOOK, SOUL_FIREBALL,
    LEGENDARY_BOOK, LEGENDARY_RANDOMIZATION_SCROLL, LEGENDARY_DP, LEGENDARY_FIREBALL, LEGENDARY_SOUL_TRACKER,
    ULTIMATE_BOOK, ULTIMATE_RANDOMIZATION_SCROLL, ULTIMATE_DP, ULTIMATE_FIREBALL, ULTIMATE_SOUL_TRACKER,
    ELITE_BOOK, ELITE_RANDOMIZATION_SCROLL, ELITE_DP, ELITE_FIREBALL, ELITE_SOUL_TRACKER,
    UNIQUE_BOOK, UNIQUE_RANDOMIZATION_SCROLL, UNIQUE_DP, UNIQUE_FIREBALL, UNIQUE_SOUL_TRACKER,
    SIMPLE_BOOK, SIMPLE_RANDOMIZATION_SCROLL, SIMPLE_DP, SIMPLE_FIREBALL, SIMPLE_SOUL_TRACKER,
    //
    FACTION_CRYSTAL, FACTION_MCMMO_BOOSTER, FACTION_XP_BOOSTER,
    MCMMO_CREDIT_VOUCHER, MCMMO_XP_VOUCHER, MCMMO_LEVEL_VOUCHER,
    BLACK_SCROLL, WHITE_SCROLL, TRANSMOG_SCROLL, ARMOR_ENCHANTMENT_ORB, WEAPON_ENCHANTMENT_ORB,
    EXPLOSIVE_CAKE, EXPERIENCE_BOTTLE, BANKNOTE, ITEM_NAME_TAG, MYSTERY_MOB_SPAWNER, SOUL_GEM,
    HALLOWEEN_CANDY, CHRISTMAS_CANDY, CHRISTMAS_EGGNOG, MYSTERY_DUST, SPACE_DRINK, SPACE_FIREWORK,
}
